async (page) => {
  const test = await page.context().newPage();
  const errors = [];
  test.on('pageerror', e => errors.push(e.message));
  await test.route('**/*', route => route.request().url().startsWith('http://127.0.0.1:8000/') ? route.continue() : route.abort());
  try {
    await test.goto('http://127.0.0.1:8000');
    let snapshot;
    await test.route('**/api/snapshot', async route => {
      const response = await route.fetch(); if(response.ok()) snapshot = await response.json();
      await route.fulfill({response});
    });
    await test.locator('#file').setInputFiles('game_web/tests/parity_snapshot.bin');
    await test.waitForFunction(() => window.gameWebDiagnostics?.().source === 'file');
    const initial = await test.evaluate(() => window.gameWebDiagnostics());
    if (initial.fov !== 60 || initial.cameraPosition.join() !== '0,-7,3') throw new Error('Camera did not seed from Blender');
    await test.locator('canvas').click();
    await test.waitForFunction(() => document.pointerLockElement !== null);
    await test.keyboard.down('w');
    await test.waitForFunction(() => window.gameWebDiagnostics().cameraPosition[1] > -6.9);
    await test.keyboard.up('w');
    await test.keyboard.press('Escape');
    await test.waitForFunction(() => document.pointerLockElement === null);
    await test.locator('#reset-camera').click();
    const reset = await test.evaluate(() => window.gameWebDiagnostics().cameraPosition);
    if (reset.join() !== '0,-7,3') throw new Error('Reset camera did not restore pose');
    await test.locator('#frame').click();
    const framed = await test.evaluate(() => window.gameWebDiagnostics().cameraPosition);
    await test.locator('#live').click();
    await test.waitForFunction(() => window.gameWebDiagnostics().source==='live' && window.gameWebDiagnostics().revision>=0);
    const livePose = await test.evaluate(() => window.gameWebDiagnostics().cameraPosition);
    if(livePose.join()!==framed.join())throw new Error('Switching to live moved camera');
    await test.locator('#file').setInputFiles('game_web/tests/parity_snapshot.bin');
    await test.waitForFunction(() => window.gameWebDiagnostics().source==='file');
    await test.evaluate(() => {
      const transfer=new DataTransfer();transfer.items.add(new File(['bad'],'bad.bin'));
      const input=document.getElementById('file');input.files=transfer.files;input.dispatchEvent(new Event('change'));
    });
    await test.waitForFunction(() => !document.getElementById('error').hidden);
    const afterInvalid=await test.evaluate(()=>window.gameWebDiagnostics());
    if(afterInvalid.source!=='file'||afterInvalid.meshCount!==1||afterInvalid.cameraPosition.join()!=='0,-7,3')throw new Error('Invalid snapshot replaced scene');
    await test.setViewportSize({width:600,height:700});
    await test.waitForFunction(()=>window.gameWebDiagnostics().aspect<1.2);
    const result = await test.evaluate(async snapshot => {
      const THREE = await import('/vendor/three/three.module.js');
      const { DebugCamera } = await import('/camera.js');
      const { SceneResources } = await import('/resources.js');
      const { lightParameters } = await import('/lighting.js');
      const assert = (condition, message) => { if (!condition) throw new Error(message); };
      const near = (a,b,t=1e-5) => Math.abs(a-b)<t;
      const cam = new THREE.PerspectiveCamera(60,1,0.01,1000);
      const controller = new DebugCamera(cam, document.createElement('canvas'));
      controller.seed(snapshot.initialCamera);
      const position = cam.position.clone(); controller.look(120, -25);
      assert(cam.position.equals(position),'Mouse look translated camera');
      controller.seed({position:[99,99,99],forward:[1,0,0],up:[0,0,1]});
      assert(cam.position.equals(position),'Later update overwrote debug camera');
      controller.reset(); controller.keys.add('KeyW');
      for(let i=0;i<60;i++)controller.move(1/60);
      assert(near(cam.position.y,3), 'Movement speed not 10 units/sec');
      controller.reset(); controller.keys.add('KeyW');
      for(let i=0;i<30;i++)controller.move(1/30);
      assert(near(cam.position.y,3),'Movement varies with frame rate');
      controller.reset(); controller.keys.add('KeyE'); controller.keys.add('ShiftLeft'); controller.move(0.1);
      assert(near(cam.position.z,8),'Vertical boosted movement');
      window.dispatchEvent(new Event('blur')); assert(controller.keys.size===0,'Blur stuck keys');
      controller.seed({position:[0,0,0],forward:[0,0,1],up:[0,1,0]},true);
      controller.look(1,1); assert(cam.quaternion.toArray().every(Number.isFinite),'Vertical view became invalid');

      const scene = new THREE.Scene(); const resources = new SceneResources(scene);
      await resources.apply(snapshot);
      const geometry = resources.meshes.get(1).geometry;
      const material = resources.meshes.get(1).material;
      const uploads = resources.geometryUploads;
      const delta = object => ({kind:'delta',batches:[{objects:[object],materials:[],images:[],deleted:[]}]});
      for(let i=0;i<20;i++)await resources.apply(delta({id:1,position:[i*0.01,0,0]}));
      assert(resources.meshes.get(1).geometry===geometry && resources.geometryUploads===uploads,'Transform reuploaded geometry');
      assert(resources.meshes.get(1).material===material,'Transform replaced material');
      await resources.apply(delta({...snapshot.objects[0],id:4}));
      assert(resources.meshes.get(4).material===material,'Material was not shared by ID');
      await resources.apply({kind:'delta',batches:[{objects:[],materials:[],images:[],deleted:[4]}]});
      let geometryDisposed=false;geometry.addEventListener('dispose',()=>geometryDisposed=true);
      const changedMesh=structuredClone(snapshot.objects[0].mesh);changedMesh.positions[0]-=0.25;
      await resources.apply(delta({id:1,mesh:changedMesh}));
      assert(geometryDisposed&&resources.meshes.get(1).geometry!==geometry,'Mesh replacement did not retire geometry');
      await resources.apply(delta({id:1,visible:false})); assert(!resources.meshes.get(1).visible,'Visibility ignored');
      await resources.apply(delta({id:1,visible:true,position:[0,0,0]}));
      assert(resources.textures.size===1,'Texture not loaded/shared');
      const texture = resources.textures.get(21).texture;
      assert(texture.flipY===false && texture.colorSpace===THREE.LinearSRGBColorSpace,'Incorrect color space / UV origin');
      assert(material.color.r===1,'Texture multiplied scalar instead of replacing it');
      await resources.apply({kind:'delta',batches:[{objects:[],materials:[{...snapshot.materials[0],metallicImage:21,roughnessImage:21}],images:[],deleted:[]}]});
      assert(material.roughness===1 && material.metalness===1,'Texture/scalar precedence mismatch');
      let compiled={fragmentShader:'#include <roughnessmap_fragment>\n#include <metalnessmap_fragment>\n#include <lights_pars_begin>'};
      material.onBeforeCompile(compiled);
      assert(compiled.fragmentShader.includes('texelRoughness.r')&&compiled.fragmentShader.includes('texelMetalness.r'),'Wrong scalar channels');
      assert(compiled.fragmentShader.includes('float( angleCosine > coneCosine )'),'Spotlight not hard edged');
      await resources.apply({kind:'delta',batches:[{objects:[],materials:[{...snapshot.materials[0],emission:[0.2,0.3,0.4,1],emissionStrength:2}],images:[],deleted:[]}]});
      assert(resources.materials.get(11).isMeshBasicMaterial,'Native emission should be unlit');
      assert(near(resources.materials.get(11).color.r,0.4),'Emission scalar mismatch');
      // Missing image initially uses scalars; a later image delta updates shared materials.
      await resources.apply({kind:'delta',batches:[{objects:[],materials:[{...snapshot.materials[0],colorImage:22}],images:[],deleted:[]}]});
      assert(resources.materials.get(11).map===null,'Missing image did not use scalar fallback');
      const replacementURL='data:application/octet-stream;base64,'+btoa(String.fromCharCode(128,64,32,255));
      await resources.apply({kind:'delta',batches:[{objects:[],materials:[],images:[{id:22,width:1,height:1,version:'replacement',url:replacementURL}],deleted:[]}]});
      assert(resources.materials.get(11).map.image.data[0]===128,'Late image did not update material');
      let textureDisposed=false;
      resources.materials.get(11).map.addEventListener('dispose',()=>textureDisposed=true);
      await resources.apply({kind:'delta',batches:[{objects:[],materials:[],images:[{id:22,width:1,height:1,version:'next',url:replacementURL}],deleted:[]}]});
      assert(textureDisposed&&resources.textures.size===1,'Texture replacement leaked');
      await resources.apply(snapshot);
      assert(resources.lights.items.size===1&&!resources.lights.preview.visible,'Authored light did not replace preview');
      resources.lights.setPreview('on'); assert(resources.lights.preview.visible,'Preview toggle');
      resources.lights.setPreview('off');

      // Render the actual Three.js materials to a linear float target, EV 0.
      const renderer = new THREE.WebGLRenderer({antialias:false});
      renderer.setSize(128,128); renderer.toneMapping=THREE.NoToneMapping;
      renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFShadowMap;
      const target = new THREE.WebGLRenderTarget(128,128,{type:THREE.FloatType});
      const camera = new THREE.PerspectiveCamera(60,1,0.01,100);
      camera.up.set(0,0,1); camera.position.set(0,-5,1.5); camera.lookAt(0,0,1.5);
      const sample = (x=64,y=64) => {
        renderer.setRenderTarget(target);renderer.render(scene,camera);
        const pixel=new Float32Array(4);renderer.readRenderTargetPixels(target,x,y,1,1,pixel);
        return [...pixel];
      };
      // Unlit textured quad verifies both row orientation and linear pixels.
      await resources.apply({kind:'delta',batches:[{objects:[],materials:[{...snapshot.materials[0],emissionStrength:1,emissionImage:21}],images:[],deleted:[]}]});
      const corners = [sample(36,40),sample(92,40),sample(36,88),sample(92,88)];
      assert(corners[0][0]>corners[0][1]&&corners[0][0]>corners[0][2],'Bottom-left should be red');
      assert(corners[1][1]>corners[1][0]&&corners[1][1]>corners[1][2],'Bottom-right should be green');
      assert(corners[2][2]>corners[2][0]&&corners[2][2]>corners[2][1],'Top-left should be blue');
      assert(corners[3][0]>corners[3][2]&&corners[3][1]>corners[3][2],'Top-right should be yellow');
      const scalar = {...snapshot.materials[0],color:[0.6,0.6,0.6,1],colorImage:-1,roughness:1,metallic:0};
      await resources.apply({kind:'delta',batches:[{objects:[{id:2,position:[0,-2,1.5],light:{type:0,color:[1,1,1],power:16*Math.PI,shadows:false}}],materials:[scalar],images:[],deleted:[]}]});
      const pointNear=sample();
      await resources.apply(delta({id:2,position:[0,-4,1.5]})); const pointFar=sample();
      assert(near(pointNear[0]/pointFar[0],4,0.015),'Point inverse-square falloff');
      // Native brdf.h at N=L=V, roughness=1, albedo=.6: (.96*.6+.01)/pi.
      const nativeReference=(0.96*0.6+0.01)/Math.PI;
      assert(Math.abs(pointNear[0]/nativeReference-1)<0.05,'Direct-light result diverges from native reference >5%');
      const linearImage={id:22,width:1,height:1,version:'linear-check',url:replacementURL};
      await resources.apply({kind:'delta',batches:[{objects:[],materials:[{...scalar,emissionStrength:1,emissionImage:22}],images:[linearImage],deleted:[]}]});
      const linearPixel=sample(); assert(near(linearPixel[0],128/255,1e-5),'Color pixels were decoded as sRGB');
      await resources.apply({kind:'delta',batches:[{objects:[],materials:[{...scalar,roughnessImage:22,metallicImage:22}],images:[],deleted:[]}]});
      const mappedPBR=sample();
      await resources.apply({kind:'delta',batches:[{objects:[],materials:[{...scalar,roughness:128/255,metallic:128/255}],images:[],deleted:[]}]});
      const scalarPBR=sample();
      assert(near(mappedPBR[0],scalarPBR[0],1e-5),'GPU scalar maps do not use the red channel');
      await resources.apply({kind:'delta',batches:[{objects:[],materials:[scalar],images:[],deleted:[]}]});
      const spotRotation=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,0,-1),new THREE.Vector3(0,1,0)).toArray();
      await resources.apply(delta({id:2,position:[0,-2,1.5],rotation:spotRotation,light:{type:1,color:[1,1,1],power:16*Math.PI,angle:0.2,edgeBlend:0.9,shadows:false}}));
      const spotInside=sample(); const spotOutside=sample(94,64);
      assert(near(spotInside[0],pointNear[0],0.001),'Spot intensity should equal point inside cone');
      assert(spotOutside[0]<1e-6,'Spot outside cone should be black');
      await resources.apply(delta({id:2,light:{type:2,color:[1,1,1],power:1361,shadows:true}}));
      const sun=sample();
      const solar=lightParameters({type:2,color:[1,1,1],power:1361});
      assert(near(sun[0]/pointNear[0],solar.color.r,0.02),'Sun irradiance conversion mismatch');
      const shadow=resources.lights.items.get(2).shadow;
      assert(shadow.map!==null&&shadow.camera.far>shadow.camera.near,'Sun shadow not allocated/fitted');
      const oldShadow=shadow.map;let shadowDisposed=false;oldShadow.addEventListener('dispose',()=>shadowDisposed=true);
      await resources.apply(delta({id:2,light:{type:2,color:[1,1,1],power:1361,shadows:false}}));
      assert(shadowDisposed&&resources.lights.items.get(2).shadow.map===null,'Disabled shadow leaked');
      const blocker = {id:3,name:'Shadow blocker',position:[-0.5,-1,1.5],rotation:[0,0,0,1],scale:[1,1,1],visible:true,
        mesh:{positions:[-.18,0,-.18,.18,0,-.18,.18,0,.18,-.18,0,.18],normals:[0,-1,0,0,-1,0,0,-1,0,0,-1,0],uvs:[],indices:[0,1,2,0,2,3],materialIds:[11]}};
      const diagonal = new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,0,-1),new THREE.Vector3(.5,1,0).normalize()).toArray();
      await resources.apply(delta(blocker));
      const shadows=[];
      for(const type of [0,1,2]) {
        const light={type,color:[1,1,1],power:type===2?1361:16*Math.PI,angle:0.5,shadows:true};
        await resources.apply(delta({id:2,position:[-1,-2,1.5],rotation:diagonal,light}));
        const occluded=sample();
        await resources.apply(delta({id:2,light:{...light,shadows:false}}));
        const unoccluded=sample();
        assert(occluded[0]<unoccluded[0]*0.25,`Light ${type} did not cast an actual shadow`);
        shadows.push({type,occluded:occluded[0],unoccluded:unoccluded[0]});
      }
      await resources.apply({kind:'delta',batches:[{objects:[],materials:[],images:[],deleted:[1,2,3]}]});
      assert(resources.meshes.size===0&&resources.materials.size===0&&resources.textures.size===0&&resources.lights.items.size===0,'Deletion leaked resources');
      const diagnostics={pointNear,pointFar,nativeReference,nativeRelativeDifference:pointNear[0]/nativeReference-1,spotInside,spotOutside,sun,corners,shadows,linearPixel,mappedPBR,scalarPBR};
      resources.dispose(); target.dispose(); renderer.dispose();renderer.forceContextLoss();
      return diagnostics;
    }, snapshot);
    if(errors.length)throw new Error(errors.join('\n'));
    return {initial,result,errors};
  } finally { await test.close(); }
}
