# automatically generated by the FlatBuffers compiler, do not modify

# namespace: LiveLink

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PointLight(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 4

    # PointLight
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PointLight
    def Energy(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreatePointLight(builder, energy):
    builder.Prep(4, 4)
    builder.PrependFloat32(energy)
    return builder.Offset()
