# automatically generated by the FlatBuffers compiler, do not modify

# namespace: LiveLink

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Update(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Update()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUpdate(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Update
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Update
    def Objects(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Blender.LiveLink.Object import Object
            obj = Object()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Update
    def ObjectsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Update
    def ObjectsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def UpdateStart(builder):
    builder.StartObject(1)

def Start(builder):
    UpdateStart(builder)

def UpdateAddObjects(builder, objects):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(objects), 0)

def AddObjects(builder, objects):
    UpdateAddObjects(builder, objects)

def UpdateStartObjectsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartObjectsVector(builder, numElems):
    return UpdateStartObjectsVector(builder, numElems)

def UpdateEnd(builder):
    return builder.EndObject()

def End(builder):
    return UpdateEnd(builder)
