// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BLENDERLIVELINK_BLENDER_LIVELINK_H_
#define FLATBUFFERS_GENERATED_BLENDERLIVELINK_BLENDER_LIVELINK_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace Blender {
namespace LiveLink {

struct Vec3;

struct Vec4;

struct Quat;

struct Vertex;

struct Mesh;
struct MeshBuilder;

struct RigidBody;

struct PointLight;

struct SpotLight;

struct Light;
struct LightBuilder;

struct Object;
struct ObjectBuilder;

struct Update;
struct UpdateBuilder;

enum LightType : int8_t {
  LightType_Point = 0,
  LightType_Spot = 1,
  LightType_Sun = 2,
  LightType_Area = 3,
  LightType_MIN = LightType_Point,
  LightType_MAX = LightType_Area
};

inline const LightType (&EnumValuesLightType())[4] {
  static const LightType values[] = {
    LightType_Point,
    LightType_Spot,
    LightType_Sun,
    LightType_Area
  };
  return values;
}

inline const char * const *EnumNamesLightType() {
  static const char * const names[5] = {
    "Point",
    "Spot",
    "Sun",
    "Area",
    nullptr
  };
  return names;
}

inline const char *EnumNameLightType(LightType e) {
  if (::flatbuffers::IsOutRange(e, LightType_Point, LightType_Area)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLightType()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec4 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  float w_;

 public:
  Vec4()
      : x_(0),
        y_(0),
        z_(0),
        w_(0) {
  }
  Vec4(float _x, float _y, float _z, float _w)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)),
        w_(::flatbuffers::EndianScalar(_w)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
  float w() const {
    return ::flatbuffers::EndianScalar(w_);
  }
};
FLATBUFFERS_STRUCT_END(Vec4, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Quat FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  float w_;

 public:
  Quat()
      : x_(0),
        y_(0),
        z_(0),
        w_(0) {
  }
  Quat(float _x, float _y, float _z, float _w)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)),
        w_(::flatbuffers::EndianScalar(_w)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
  float w() const {
    return ::flatbuffers::EndianScalar(w_);
  }
};
FLATBUFFERS_STRUCT_END(Quat, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vertex FLATBUFFERS_FINAL_CLASS {
 private:
  Blender::LiveLink::Vec4 position_;
  Blender::LiveLink::Vec4 normal_;

 public:
  Vertex()
      : position_(),
        normal_() {
  }
  Vertex(const Blender::LiveLink::Vec4 &_position, const Blender::LiveLink::Vec4 &_normal)
      : position_(_position),
        normal_(_normal) {
  }
  const Blender::LiveLink::Vec4 &position() const {
    return position_;
  }
  const Blender::LiveLink::Vec4 &normal() const {
    return normal_;
  }
};
FLATBUFFERS_STRUCT_END(Vertex, 32);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) RigidBody FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t is_dynamic_;
  int8_t padding0__;  int16_t padding1__;
  float mass_;

 public:
  RigidBody()
      : is_dynamic_(0),
        padding0__(0),
        padding1__(0),
        mass_(0) {
    (void)padding0__;
    (void)padding1__;
  }
  RigidBody(bool _is_dynamic, float _mass)
      : is_dynamic_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_is_dynamic))),
        padding0__(0),
        padding1__(0),
        mass_(::flatbuffers::EndianScalar(_mass)) {
    (void)padding0__;
    (void)padding1__;
  }
  bool is_dynamic() const {
    return ::flatbuffers::EndianScalar(is_dynamic_) != 0;
  }
  float mass() const {
    return ::flatbuffers::EndianScalar(mass_);
  }
};
FLATBUFFERS_STRUCT_END(RigidBody, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) PointLight FLATBUFFERS_FINAL_CLASS {
 private:
  float power_;

 public:
  PointLight()
      : power_(0) {
  }
  PointLight(float _power)
      : power_(::flatbuffers::EndianScalar(_power)) {
  }
  float power() const {
    return ::flatbuffers::EndianScalar(power_);
  }
};
FLATBUFFERS_STRUCT_END(PointLight, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) SpotLight FLATBUFFERS_FINAL_CLASS {
 private:
  float power_;
  float beam_angle_;
  float edge_blend_;

 public:
  SpotLight()
      : power_(0),
        beam_angle_(0),
        edge_blend_(0) {
  }
  SpotLight(float _power, float _beam_angle, float _edge_blend)
      : power_(::flatbuffers::EndianScalar(_power)),
        beam_angle_(::flatbuffers::EndianScalar(_beam_angle)),
        edge_blend_(::flatbuffers::EndianScalar(_edge_blend)) {
  }
  float power() const {
    return ::flatbuffers::EndianScalar(power_);
  }
  float beam_angle() const {
    return ::flatbuffers::EndianScalar(beam_angle_);
  }
  float edge_blend() const {
    return ::flatbuffers::EndianScalar(edge_blend_);
  }
};
FLATBUFFERS_STRUCT_END(SpotLight, 12);

struct Mesh FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MeshBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERTICES = 4,
    VT_INDICES = 6
  };
  const ::flatbuffers::Vector<const Blender::LiveLink::Vertex *> *vertices() const {
    return GetPointer<const ::flatbuffers::Vector<const Blender::LiveLink::Vertex *> *>(VT_VERTICES);
  }
  const ::flatbuffers::Vector<uint32_t> *indices() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_INDICES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VERTICES) &&
           verifier.VerifyVector(vertices()) &&
           VerifyOffset(verifier, VT_INDICES) &&
           verifier.VerifyVector(indices()) &&
           verifier.EndTable();
  }
};

struct MeshBuilder {
  typedef Mesh Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vertices(::flatbuffers::Offset<::flatbuffers::Vector<const Blender::LiveLink::Vertex *>> vertices) {
    fbb_.AddOffset(Mesh::VT_VERTICES, vertices);
  }
  void add_indices(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> indices) {
    fbb_.AddOffset(Mesh::VT_INDICES, indices);
  }
  explicit MeshBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Mesh> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Mesh>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Mesh> CreateMesh(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Blender::LiveLink::Vertex *>> vertices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> indices = 0) {
  MeshBuilder builder_(_fbb);
  builder_.add_indices(indices);
  builder_.add_vertices(vertices);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Mesh> CreateMeshDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<Blender::LiveLink::Vertex> *vertices = nullptr,
    const std::vector<uint32_t> *indices = nullptr) {
  auto vertices__ = vertices ? _fbb.CreateVectorOfStructs<Blender::LiveLink::Vertex>(*vertices) : 0;
  auto indices__ = indices ? _fbb.CreateVector<uint32_t>(*indices) : 0;
  return Blender::LiveLink::CreateMesh(
      _fbb,
      vertices__,
      indices__);
}

struct Light FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LightBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_COLOR = 6,
    VT_USE_SHADOW = 8,
    VT_POINT_LIGHT = 10,
    VT_SPOT_LIGHT = 12
  };
  Blender::LiveLink::LightType type() const {
    return static_cast<Blender::LiveLink::LightType>(GetField<int8_t>(VT_TYPE, 0));
  }
  const Blender::LiveLink::Vec3 *color() const {
    return GetStruct<const Blender::LiveLink::Vec3 *>(VT_COLOR);
  }
  bool use_shadow() const {
    return GetField<uint8_t>(VT_USE_SHADOW, 0) != 0;
  }
  const Blender::LiveLink::PointLight *point_light() const {
    return GetStruct<const Blender::LiveLink::PointLight *>(VT_POINT_LIGHT);
  }
  const Blender::LiveLink::SpotLight *spot_light() const {
    return GetStruct<const Blender::LiveLink::SpotLight *>(VT_SPOT_LIGHT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<Blender::LiveLink::Vec3>(verifier, VT_COLOR, 4) &&
           VerifyField<uint8_t>(verifier, VT_USE_SHADOW, 1) &&
           VerifyField<Blender::LiveLink::PointLight>(verifier, VT_POINT_LIGHT, 4) &&
           VerifyField<Blender::LiveLink::SpotLight>(verifier, VT_SPOT_LIGHT, 4) &&
           verifier.EndTable();
  }
};

struct LightBuilder {
  typedef Light Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(Blender::LiveLink::LightType type) {
    fbb_.AddElement<int8_t>(Light::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_color(const Blender::LiveLink::Vec3 *color) {
    fbb_.AddStruct(Light::VT_COLOR, color);
  }
  void add_use_shadow(bool use_shadow) {
    fbb_.AddElement<uint8_t>(Light::VT_USE_SHADOW, static_cast<uint8_t>(use_shadow), 0);
  }
  void add_point_light(const Blender::LiveLink::PointLight *point_light) {
    fbb_.AddStruct(Light::VT_POINT_LIGHT, point_light);
  }
  void add_spot_light(const Blender::LiveLink::SpotLight *spot_light) {
    fbb_.AddStruct(Light::VT_SPOT_LIGHT, spot_light);
  }
  explicit LightBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Light> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Light>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Light> CreateLight(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Blender::LiveLink::LightType type = Blender::LiveLink::LightType_Point,
    const Blender::LiveLink::Vec3 *color = nullptr,
    bool use_shadow = false,
    const Blender::LiveLink::PointLight *point_light = nullptr,
    const Blender::LiveLink::SpotLight *spot_light = nullptr) {
  LightBuilder builder_(_fbb);
  builder_.add_spot_light(spot_light);
  builder_.add_point_light(point_light);
  builder_.add_color(color);
  builder_.add_use_shadow(use_shadow);
  builder_.add_type(type);
  return builder_.Finish();
}

struct Object FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ObjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_UNIQUE_ID = 6,
    VT_VISIBILITY = 8,
    VT_LOCATION = 10,
    VT_SCALE = 12,
    VT_ROTATION = 14,
    VT_MESH = 16,
    VT_RIGID_BODY = 18,
    VT_LIGHT = 20
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  int32_t unique_id() const {
    return GetField<int32_t>(VT_UNIQUE_ID, 0);
  }
  bool visibility() const {
    return GetField<uint8_t>(VT_VISIBILITY, 0) != 0;
  }
  const Blender::LiveLink::Vec3 *location() const {
    return GetStruct<const Blender::LiveLink::Vec3 *>(VT_LOCATION);
  }
  const Blender::LiveLink::Vec3 *scale() const {
    return GetStruct<const Blender::LiveLink::Vec3 *>(VT_SCALE);
  }
  const Blender::LiveLink::Quat *rotation() const {
    return GetStruct<const Blender::LiveLink::Quat *>(VT_ROTATION);
  }
  const Blender::LiveLink::Mesh *mesh() const {
    return GetPointer<const Blender::LiveLink::Mesh *>(VT_MESH);
  }
  const Blender::LiveLink::RigidBody *rigid_body() const {
    return GetStruct<const Blender::LiveLink::RigidBody *>(VT_RIGID_BODY);
  }
  const Blender::LiveLink::Light *light() const {
    return GetPointer<const Blender::LiveLink::Light *>(VT_LIGHT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int32_t>(verifier, VT_UNIQUE_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_VISIBILITY, 1) &&
           VerifyField<Blender::LiveLink::Vec3>(verifier, VT_LOCATION, 4) &&
           VerifyField<Blender::LiveLink::Vec3>(verifier, VT_SCALE, 4) &&
           VerifyField<Blender::LiveLink::Quat>(verifier, VT_ROTATION, 4) &&
           VerifyOffset(verifier, VT_MESH) &&
           verifier.VerifyTable(mesh()) &&
           VerifyField<Blender::LiveLink::RigidBody>(verifier, VT_RIGID_BODY, 4) &&
           VerifyOffset(verifier, VT_LIGHT) &&
           verifier.VerifyTable(light()) &&
           verifier.EndTable();
  }
};

struct ObjectBuilder {
  typedef Object Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Object::VT_NAME, name);
  }
  void add_unique_id(int32_t unique_id) {
    fbb_.AddElement<int32_t>(Object::VT_UNIQUE_ID, unique_id, 0);
  }
  void add_visibility(bool visibility) {
    fbb_.AddElement<uint8_t>(Object::VT_VISIBILITY, static_cast<uint8_t>(visibility), 0);
  }
  void add_location(const Blender::LiveLink::Vec3 *location) {
    fbb_.AddStruct(Object::VT_LOCATION, location);
  }
  void add_scale(const Blender::LiveLink::Vec3 *scale) {
    fbb_.AddStruct(Object::VT_SCALE, scale);
  }
  void add_rotation(const Blender::LiveLink::Quat *rotation) {
    fbb_.AddStruct(Object::VT_ROTATION, rotation);
  }
  void add_mesh(::flatbuffers::Offset<Blender::LiveLink::Mesh> mesh) {
    fbb_.AddOffset(Object::VT_MESH, mesh);
  }
  void add_rigid_body(const Blender::LiveLink::RigidBody *rigid_body) {
    fbb_.AddStruct(Object::VT_RIGID_BODY, rigid_body);
  }
  void add_light(::flatbuffers::Offset<Blender::LiveLink::Light> light) {
    fbb_.AddOffset(Object::VT_LIGHT, light);
  }
  explicit ObjectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Object> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Object>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Object> CreateObject(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    int32_t unique_id = 0,
    bool visibility = false,
    const Blender::LiveLink::Vec3 *location = nullptr,
    const Blender::LiveLink::Vec3 *scale = nullptr,
    const Blender::LiveLink::Quat *rotation = nullptr,
    ::flatbuffers::Offset<Blender::LiveLink::Mesh> mesh = 0,
    const Blender::LiveLink::RigidBody *rigid_body = nullptr,
    ::flatbuffers::Offset<Blender::LiveLink::Light> light = 0) {
  ObjectBuilder builder_(_fbb);
  builder_.add_light(light);
  builder_.add_rigid_body(rigid_body);
  builder_.add_mesh(mesh);
  builder_.add_rotation(rotation);
  builder_.add_scale(scale);
  builder_.add_location(location);
  builder_.add_unique_id(unique_id);
  builder_.add_name(name);
  builder_.add_visibility(visibility);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Object> CreateObjectDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    int32_t unique_id = 0,
    bool visibility = false,
    const Blender::LiveLink::Vec3 *location = nullptr,
    const Blender::LiveLink::Vec3 *scale = nullptr,
    const Blender::LiveLink::Quat *rotation = nullptr,
    ::flatbuffers::Offset<Blender::LiveLink::Mesh> mesh = 0,
    const Blender::LiveLink::RigidBody *rigid_body = nullptr,
    ::flatbuffers::Offset<Blender::LiveLink::Light> light = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return Blender::LiveLink::CreateObject(
      _fbb,
      name__,
      unique_id,
      visibility,
      location,
      scale,
      rotation,
      mesh,
      rigid_body,
      light);
}

struct Update FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UpdateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJECTS = 4,
    VT_DELETED_OBJECT_UIDS = 6
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<Blender::LiveLink::Object>> *objects() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Blender::LiveLink::Object>> *>(VT_OBJECTS);
  }
  const ::flatbuffers::Vector<int32_t> *deleted_object_uids() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_DELETED_OBJECT_UIDS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_OBJECTS) &&
           verifier.VerifyVector(objects()) &&
           verifier.VerifyVectorOfTables(objects()) &&
           VerifyOffset(verifier, VT_DELETED_OBJECT_UIDS) &&
           verifier.VerifyVector(deleted_object_uids()) &&
           verifier.EndTable();
  }
};

struct UpdateBuilder {
  typedef Update Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_objects(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Blender::LiveLink::Object>>> objects) {
    fbb_.AddOffset(Update::VT_OBJECTS, objects);
  }
  void add_deleted_object_uids(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> deleted_object_uids) {
    fbb_.AddOffset(Update::VT_DELETED_OBJECT_UIDS, deleted_object_uids);
  }
  explicit UpdateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Update> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Update>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Update> CreateUpdate(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Blender::LiveLink::Object>>> objects = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> deleted_object_uids = 0) {
  UpdateBuilder builder_(_fbb);
  builder_.add_deleted_object_uids(deleted_object_uids);
  builder_.add_objects(objects);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Update> CreateUpdateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<Blender::LiveLink::Object>> *objects = nullptr,
    const std::vector<int32_t> *deleted_object_uids = nullptr) {
  auto objects__ = objects ? _fbb.CreateVector<::flatbuffers::Offset<Blender::LiveLink::Object>>(*objects) : 0;
  auto deleted_object_uids__ = deleted_object_uids ? _fbb.CreateVector<int32_t>(*deleted_object_uids) : 0;
  return Blender::LiveLink::CreateUpdate(
      _fbb,
      objects__,
      deleted_object_uids__);
}

inline const Blender::LiveLink::Update *GetUpdate(const void *buf) {
  return ::flatbuffers::GetRoot<Blender::LiveLink::Update>(buf);
}

inline const Blender::LiveLink::Update *GetSizePrefixedUpdate(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Blender::LiveLink::Update>(buf);
}

inline bool VerifyUpdateBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Blender::LiveLink::Update>(nullptr);
}

inline bool VerifySizePrefixedUpdateBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Blender::LiveLink::Update>(nullptr);
}

inline void FinishUpdateBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Blender::LiveLink::Update> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedUpdateBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Blender::LiveLink::Update> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace LiveLink
}  // namespace Blender

#endif  // FLATBUFFERS_GENERATED_BLENDERLIVELINK_BLENDER_LIVELINK_H_
